title: eduserveMinimal
logo: https://raw.githubusercontent.com/hiruthicShaSS/eduserveMinimal/main/assets/appIcon.png
description: Something that is responsive
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
