title: eduserveMinimal
logo: https://github.com/hiruthicShaSS/eduserveMinimal/blob/main/assets/appIcon.png
description: Something that is responsive
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
