name: Test Action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - name: Print boi
        run: echo "Hey"
