name: VirusTotal Scan
on: [push, pull_request, workflow_dispatch]
jobs:
  virustotal-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        env:
          VIRUS_TOTAL_API_KEY: ${{ secrets.VIRUS_TOTAL_API_KEY }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'
      
      - name: Build application
      - run: flutter pub get
      - run: flutter build apk --target lib/main_production.dart --flavor production --split-per-abi
      
      - name: Upload and get results
      - run: curl --request POST --url https://www.virustotal.com/api/v3/files --header "x-apikey: $VIRUS_TOTAL_API_KEY" --header "Accept: application/json" --header "Content-Type: multipart/form-data" -F "file=@build/app/outputs/apk/production/release/app-production-release.apk"
      - run: sha256sum build/app/outputs/apk/production/release/app-production-release.apk | hash.txt
      - run: curl --request GET --url https://www.virustotal.com/api/v3/files/$(cat hash.txt) --header "x-apikey: $VIRUS_TOTAL_API_KEY"
